### ISSUE TITLE
Cambiar el icon

### ISSUE THREAD

**Issue by omiras** [Singulars2021/singusaurus#2]
Investigar como cambiar el icono de la Web, por el mismo que aparece en la organización 

**Recordar**: Esto hay que hacerlo a la "Docsaurus" _way_. Investigar como es la manera adecuada de cambiar el icono de la página usando la configuración de este software.

**Comment by omiras** [comment]
Hola @homell100 . A propuesta de @aguzsol y secundado por la clase, el icono será el siguiente: https://www.freepik.es/vector-premium/lazy-cat-working-on-laptop-vector-icono-ilustracion-gato-portatil-concepto-icono-animal_6539924.htm ;)

**Comment by homell100** [comment]
Para resolver esta issue se ha descargado el [nuevo icono](https://www.freepik.es/vector-premium/lazy-cat-working-on-laptop-vector-icono-ilustracion-gato-portatil-concepto-icono-animal_6539924.htm), se ha transformado a las extensiones .ico y .svg y se han intercambiado estas respectivas imagenes por los archivos singusaurus/static/img/favicon.ico y singusaurus/static/img/logo.svg respectivamente.
