### ISSUE TITLE
Cambiar el color principal (corporativo) de la Web

### ISSUE THREAD

**Issue by omiras** [Singulars2021/singusaurus#3]
Fijaos que hay un verde característico como color principal de esta Web (ilumina enlaces, items de menú, etc).
Cambiarlo por un azul que quede bien acorde con el logo del gato (se aceptan propuestas de colores de nuestras expertas en diseño)

**Comment by aguzsol** [comment]
Hemos cambiado el color principal por el azul #33a3ff y sus derivados (dark/light).
