### ISSUE TITLE
Estructura los ficheros .md

### ISSUE THREAD

**Issue by omiras** [Singulars2021/singusaurus#5]
Investiga como estructurar los ficheros .md de la carpeta **/docs** para que se adecue a nuestro proyecto.
Por ejemplo, vamos a intentar reproducir esta estructura:

- CSS
   - SASS
   - Bootstrap
- JavaScript
   - Eventos
   - Jquery
   - Métodos de array
   - Objetos y clases
- GIT
- Docsaurus

Cambia la información necesaria y los ficheros de configuración adecuados

**Comment by pppeedrito** [comment]
Se ha modificado el contenido de slidebars.js renombrando el contenido de la barra lateral. Para crear las estructuras de los ficheros se hace de la siguiente forma:  Titulo ['subtitulo1', 'subitulo2' etc..].
Tras ello, se ha de crear un fichero por cada subtitulo que hayamos creado con la extensión ( .md ) en la raíz  docs.
Dentro del fichero crearemos lo siguiente: 

id: subtitulo1 (valor que le damos anteriormente en el fichero slidebars.js)
title: "titulo" (visualiza en la página)
