### ISSUE TITLE
Convertir la sección de Blog en sección de Actas

### ISSUE THREAD

**Issue by omiras** [Singulars2021/singusaurus#7]
- Hacer los cambios necesarios en el código y en el formato/cotenido de los ficheros .md de la sección de blog para convertirlo en una sección de actas
- Pensar que metadatatos de los .md del blog podemos aprovechar para las actas
- Pasar el acta (provisional) de hoy como "post" de esta sección. 
- Interesante: Docsaurus usa .md, pero también mdx. Poner "estilos" en los ficheros Markdown. Seria interesante usar el color corporativo para los títulos de las actas?
- Buscar una herramienta para pasar docx a md por linia de comandos (npm?)

**Comment by LennyCC** [comment]
Hemos modificado el contenido de "Blog" en Actas== Proceedings== Daily.
Hemos modificado los metadatos para que se ajusten a nuestras necesidades, utilizando la documentación.
Hemos implementado el acta de hoy como ejemplo.
MDX ha sido usado para cambiar los estilos de los títulos del documento, al color corporativo.
Hemos intentado implementar archivos docx a md utilizando la líneas de comando nmp. 
*(Mammoth seguir investigando para md, pero sí funcina para HTML).
